name: lint
run-name: Lint
on: [push]

jobs:
    frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v3
            - name: Set Node.js 19.x
              uses: actions/setup-node@v3
              with:
                node-version: 19.x
                cache: yarn
            - name: Install dependencies
              run: yarn
            - name: Lint
              run: yarn lint

    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@v3
            - name: Set Node.js 19.x
              uses: actions/setup-node@v3
              with:
                node-version: 19.x
                cache: yarn
            - name: Install dependencies
              run: yarn
            - name: Lint
              run: yarn lint