name: test
run-name: Test
on: [push]

jobs:
    frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v3
            - name: Set Node.js 19.x
              uses: actions/setup-node@v3
              with:
                node-version: 19.x
                cache: yarn
            - name: Install dependencies
              run: yarn
            - name: Test
              run: yarn test

    backend:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: test
            DATABASE_URL: file:./test.db
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@v3
            - name: Set Node.js 19.x
              uses: actions/setup-node@v3
              with:
                node-version: 19.x
                cache: yarn
            - name: Install dependencies
              run: yarn
            - name: Migrate testing database
              run: yarn test:migrate
            - name: Test
              run: yarn test